apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: tinyblog-go.frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "tb-session=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "tb-session=x-liveness-probe"
        env:
        - name: LISTEN_ADDRESS
          value: "0.0.0.0:8080"
        - name: RECOMMEND_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: tb-configs
              key: recommend_service_address
        - name: ARTICLE_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: tb-configs
              key: article_service_address
        - name: AUTH_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: tb-configs
              key: user_service_address
        - name: USER_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: tb-configs
              key: user_service_address
        - name: SEARCH_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: tb-configs
              key: search_service_address
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080