apiVersion: v1
kind: Secret
metadata:
  name: tb-user-service-secrets
type: Opaque
data:
  jwt_secret: WVdSdGFXNXBjM1J5WVhSdmNn
stringData:
  mysql_user_db_user_password: user123456
  mysql_user_db_conn_str: user:user123456@tcp(mysql:3306)/user?loc=Local&parseTime=true
---
apiVersion: v1
kind: Secret
metadata:
  name: tb-article-service-secrets
type: Opaque
stringData:
  mysql_article_db_user_password: article123456
  mysql_article_db_conn_str: article:article123456@tcp(mysql:3306)/article?loc=Local&parseTime=true
---
apiVersion: v1
kind: Secret
metadata:
  name: tb-recommend-service-secrets
type: Opaque
stringData:
  mysql_recommend_db_user_password: recommend123456
  mysql_recommend_db_conn_str: recommend:recommend123456@tcp(mysql:3306)/recommend?loc=Local&parseTime=true
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  mysql_root_password: mysql123QWE
